/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Todoapp;

import controller.ProjectController;
import java.util.List;
import model.Project;



public class App {
    

    public static void main(String[] args) throws ClassNotFoundException {
        ProjectController projectController = new ProjectController();
        
        // project = new Project();
       // project.setName("Projeto teste");
       // project.setDescr("description");
       // projectController.save(project);
        
       Project project = new Project();
        project.setName("Projeto teste");
        project.setId(6);
        project.setDescr("description"); 
       project.setName("novo nome de projeto");
       projectController.update(project);   
       
      // List<Project>projects = projectController.getAll();
      //System.out.println("total de projetos", + projects.size());
     // projectController.removeById(3);
               
    }
}
